### ISSUE TITLE
Run with boot2docker

### ISSUE THREAD

**Issue by caueops** [mlabouardy/dockerboard#1]
How can I run on `Mac OS`?

**Comment by mlabouardy** [comment]
@cauealves you can use docker-machine to create a docker virtual machine, and then you can create your container using : 
`docker run -d -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock --name dockerboard mlabouardy/dockerboard:5.0`

**Comment by caueops** [comment]
Hello @mlabouardy, 

Yeaah, but this is not a correctly folder of socket when use `docker-machine`

But, now I'm using docker without that and works fine. ;)

**Comment by mlabouardy** [comment]
it's weird, i'm using docker-machine and docker.socket exists
[
![socket](https://cloud.githubusercontent.com/assets/10320205/15775393/faaab8a0-2981-11e6-978b-ddd16b679fda.png)
](url)

**Comment by caueops** [comment]
Yeah, I saw that was confusing.

I was looking for in my host machine =O 

Thx
